gui:
  - changed-files:
    - any-glob-to-any-file: src/gui/**/*

media-player:
  - changed-files:
    - any-glob-to-any-file: src/media_player/**/*

youtube-browser:
  - changed-files:
    - any-glob-to-any-file: src/youtube_browser/**/*

downloader:
  - changed-files:
    - any-glob-to-any-file: src/download_handler/**/*

translations:
  - changed-files:
    - any-glob-to-any-file:
      - src/languages/**/*
      - messages.pot
      - babel.cfg

ci:
  - changed-files:
    - any-glob-to-any-file: .github/workflows/**/*

tests:
  - changed-files:
    - any-glob-to-any-file: tests/**/*
